FROM python:3.10.0

WORKDIR /app

COPY requirements.txt .
COPY app.py .
COPY saved_model/1 .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]